language: node_js
node_js:
  - "node"
install:
  # install eleventy and any dependencies inside ./package.json
  - npm install
script:
  # run generator
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  target_branch: master
  fqdn: https://blunt.af
  on:
    branch: dev